name: webstore

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8001:8001"
    container_name: fastapi-backend
    volumes:
      - ./backend/src:/src
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: vuejs-frontend
    volumes:
      - ./frontend/vue-project/src:/app/src
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
