name: webstore

services:
  db:
    image: gvenzl/oracle-xe
    container_name: oracle-xe
    # environment:
    #   ORACLE_USERNAME: ${ORACLE_USERNAME}
    #   ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    #   ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET}
    #   ORACLE_PDB: ${ORACLE_PDB}  
    env_file:
      - ./db/.env             
    ports:
      - "1521:1521"                      
    volumes:
      - oracle_data2:/opt/oracle/oradata

  backend:
    build: 
      context: .\backend
    ports:
      - "8001:8001"
    container_name: fastapi-backend
    volumes:
      - .\backend\app:/code/app
    environment:
      ORACLE_USERNAME: ${ORACLE_USERNAME}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD} 
      ORACLE_DSN: ${ORACLE_DSN}
      ORACLE_PDB: ${ORACLE_PDB}
    depends_on:
      - db

  frontend:
    build: .\frontend
    ports:
      - "80:80"
    container_name: vuejs-frontend
    depends_on:
      - backend

volumes:
  oracle_data2: