name: webstore

services:
  backend:
    build: 
      context: .\backend
    ports:
      - "8001:8001"
    container_name: fastapi-backend
    volumes:
      - ./backend/code:/code
    env_file:
      - ./backend/.env

  frontend_jinja:
    build: 
      context: .\frontend_jinja
    ports:
      - "80:80"
    container_name: fastapi-frontend
    volumes:
      - ./frontend_jinja/code:/code
    depends_on:
      - backend

  frontend:
    build: .\frontend
    ports:
      - "5173:5173"
    container_name: vuejs-frontend
    volumes:
      - ./frontend/vue-project/src:/app/src
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
