name: webstore

services:
  backend:
    build: 
      context: .\backend
    ports:
      - "8001:8001"
    container_name: fastapi-backend
    volumes:
      - ./backend/code:/code
    env_file:
      - ./backend/.env