services:
  backend:
    build: .\backend
    ports:
      - "8001:8001"
    container_name: fastapi-backend
    environment:
      PORT: 8001

  frontend:
    build: .\frontend
    ports:
      - "80:80"
    container_name: vuejs-frontend
    depends_on:
      - backend
