services:
  backend:
    build: .\backend
    ports:
      - "8001:8001"
    container_name: fastapi-backend
    environment:
      PORT: 8001
    depends_on:
      - db

  frontend:
    build: .\frontend
    ports:
      - "80:80"
    container_name: vuejs-frontend
    depends_on:
      - backend

  db:
    image: gvenzl/oracle-xe:11.2.0.2-slim-faststart
    container_name: oracle
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_PASSWORD: password
    ports:
      - "1521:1521"
    volumes:
      - .\db\oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: