version: '3'
name: webstore

services:
  backend:
    build: 
      context: .\backend
    ports:
      - "8001:8001"
    container_name: fastapi-application
    environment:
      PORT: 8001
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app 
    container_name: vuejs
    container_name: fastapi-backend
    volumes:
      - ./backend/code:/code
    env_file:
      - ./backend/.env

  frontend_jinja:
    build: 
      context: .\frontend_jinja
    ports:
      - "80:80"
    container_name: fastapi-frontend
    volumes:
      - ./frontend_jinja/code:/code
    depends_on:
      - backend
