version: '3'
services:
  backend:
    build: .
    ports:
      - "8001:8001"
    container_name: fastapi-application
    environment:
      PORT: 8001
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app 
    container_name: vuejs
    depends_on:
      - backend
