/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BanerComponent: typeof import('./components/BanerComponent.vue')['default']
    BestsellerComponent: typeof import('./components/BestsellerComponent.vue')['default']
    CategoriesComponent: typeof import('./components/CategoriesComponent.vue')['default']
    FotterComponent: typeof import('./components/FotterComponent.vue')['default']
    ProductDialog: typeof import('./components/ProductDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBarComponent: typeof import('./components/TopBarComponent.vue')['default']
  }
}
