"""empty message

Revision ID: 8066b16dacc5
Revises: 
Create Date: 2025-01-27 21:23:05.762795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '8066b16dacc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # op.create_table('product',
    # sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    # sa.Column('brand', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('type_id', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.Column('price', oracle.NUMBER(precision=10, scale=2, asdecimal=False), nullable=False),
    # sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    # sa.Column('ean', sa.VARCHAR(length=13), nullable=False),
    # sa.Column('stock', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # # sa.ForeignKeyConstraint(['type'], ['type.id'], name='fk_product_type'),
    # sa.PrimaryKeyConstraint('id', name='product_pkey'),
    # oracle_resolve_synonyms=False
    # )

    op.create_table('order_head',
    sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('client_id', oracle.NUMBER(precision=36, scale=0, asdecimal=False), nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('value', oracle.NUMBER(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('delivery_form', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    sa.Column('order_date', oracle.DATE(), nullable=False),
    sa.Column('delivery_date', oracle.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=25), nullable=False),
    # sa.ForeignKeyConstraint(['formaodbioru'], ['formaodbioru.id'], name='fk_zamowienie_formaodbioru'),
    # sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_order_client'),
    # sa.ForeignKeyConstraint(['lista_zak'], ['lista_zakupow.id'], name='fk_zamowienie_lista_zak'),
    sa.PrimaryKeyConstraint('id', name='order_head_pkey')
    )

    op.create_table('order_row',
    sa.Column('order_id', oracle.NUMBER(precision=36, scale=0, asdecimal=False), nullable=False),
    sa.Column('product_id', oracle.NUMBER(precision=36, scale=0, asdecimal=False), nullable=False),
    sa.Column('quantity', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.ForeignKeyConstraint(['product'], ['product.id'], name='fk_product'),
    sa.PrimaryKeyConstraint('order_id', name='order_row_pkey'),
    oracle_resolve_synonyms=False
    )


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('logi',
    # sa.Column('uzytkownik', sa.VARCHAR(length=20), server_default=sa.text('user '), nullable=False),
    # sa.Column('opis', sa.VARCHAR(length=300), nullable=False),
    # sa.Column('kiedy', oracle.TIMESTAMP(), server_default=sa.text('systimestamp\n'), nullable=True)
    # )
    # op.create_table('koszyk_zakupowy',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=True),
    # sa.Column('created_at', oracle.DATE(), nullable=True),
    # sa.Column('modified_at', oracle.DATE(), nullable=True)
    # )
    # op.create_table('miasto',
    # sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    # sa.Column('nazwa', sa.VARCHAR(length=100), nullable=False),
    # sa.PrimaryKeyConstraint('id', name='miasto_pkey'),
    # oracle_resolve_synonyms=False
    # )
    # op.create_table('zamowienie_wiersz',
    # sa.Column('zamowienie_id', sa.INTEGER(), nullable=False),
    # sa.Column('produkt_id', sa.INTEGER(), nullable=False),
    # sa.Column('ilosc', sa.INTEGER(), nullable=False)
    # )
    # op.create_table('typ',
    # sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    # sa.Column('nazwa', sa.VARCHAR(length=150), nullable=False),
    # sa.PrimaryKeyConstraint('id', name='typ_pkey'),
    # oracle_resolve_synonyms=False
    # )
    # op.create_table('produkt',
    # sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    # sa.Column('marka', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('typ', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.Column('cena', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.Column('nazwa', sa.VARCHAR(length=150), nullable=False),
    # sa.Column('ean', sa.VARCHAR(length=13), nullable=False),
    # sa.Column('ilosc_magazyn', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.ForeignKeyConstraint(['typ'], ['typ.id'], name='fk_produkt_typ'),
    # sa.PrimaryKeyConstraint('id', name='produkt_pkey'),
    # oracle_resolve_synonyms=False
    # )
    # op.create_table('klient',
    # sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    # sa.Column('imie', sa.VARCHAR(length=150), nullable=False),
    # sa.Column('nazwisko', sa.VARCHAR(length=150), nullable=False),
    # sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('telefon', sa.VARCHAR(length=9), nullable=False),
    # sa.Column('miasto', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.Column('kod_pocztowy', sa.VARCHAR(length=15), nullable=False),
    # sa.Column('ulica', sa.VARCHAR(length=15), nullable=False),
    # sa.Column('nip', sa.VARCHAR(length=12), nullable=True),
    # sa.Column('nazwa_firmy', sa.VARCHAR(length=150), nullable=True),
    # sa.ForeignKeyConstraint(['miasto'], ['miasto.id'], name='fk_klient_miasto'),
    # sa.PrimaryKeyConstraint('id', name='klient_pkey'),
    # oracle_resolve_synonyms=False
    # )
    # op.create_table('lista_zakupow',
    # sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    # sa.Column('id_listy', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.Column('produkt', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.Column('ilosc', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.ForeignKeyConstraint(['produkt'], ['produkt.id'], name='fk_lista_zakupow_produkt'),
    # sa.PrimaryKeyConstraint('id', name='lista_zakupow_pkey'),
    # oracle_resolve_synonyms=False
    # )
    # op.create_table('zamowienie',
    # sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    # sa.Column('klient_id', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.Column('nr_zamowienia', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('formaplatnosci', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('wartosc', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.Column('formaodbioru', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.Column('data_zlozenia', oracle.DATE(), nullable=False),
    # sa.Column('data_wyslania', oracle.DATE(), nullable=True),
    # sa.Column('status', sa.VARCHAR(length=25), nullable=False),
    # sa.Column('lista_zak', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    # sa.ForeignKeyConstraint(['formaodbioru'], ['formaodbioru.id'], name='fk_zamowienie_formaodbioru'),
    # sa.ForeignKeyConstraint(['klient_id'], ['klient.id'], name='fk_zamowienie_klient'),
    # sa.ForeignKeyConstraint(['lista_zak'], ['lista_zakupow.id'], name='fk_zamowienie_lista_zak'),
    # sa.PrimaryKeyConstraint('id', name='zamowienie_pkey')
    # )
    # op.create_index('status_x', 'zamowienie', ['status'], unique=False)
    # op.create_index('klient_x', 'zamowienie', ['klient_id'], unique=False)
    # op.create_table('formaodbioru',
    # sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    # sa.Column('nazwa', sa.VARCHAR(length=150), nullable=True),
    # sa.PrimaryKeyConstraint('id', name='formaodbioru_pkey')
    # )
    # ### end Alembic commands ###
